version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=protestos
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=protestos
    volumes:
      - ./config/protestos.sql:/docker-entrypoint-initdb.d/protestos.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge